name: test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Test
              run: npm run test
